spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: eh@redis
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 5000ms

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 12
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.eh.cloud.auth.model.entity.*

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
