server:
  port: 9100
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaltZone: http://localhost:9000/eureka/

spring:
  application:
    name: userservice
  jpa:
    open-in-view: true
    hibernate.ddl-auto: none
    show-sql: true
    database: h2
  datasource:
    url: jdbc:h2:mem:dbtest;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    platform: h2
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true