zuul:
  ignoredServices: '*'
  routes:
    user:
      path: /auth/**
      serviceId: AUTH
      sensitive-headers: Cookie,Set-Cookie
    consumer:
      path: /consumer/**
      serviceId: CONSUMERSERVICE
      sensitive-headers: Cookie,Set-Cookie

