server:
  port: 13000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ravitation/cloud/config-center/config
          username: ravitation
          password: cph199006006
