spring:
  application:
    name: servicediscovery
server:
  port: 9001

eureka:
  instance:
    hostname: sdpeer1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eh:root@sdpeer2:9002/eureka/,http://eh:root@sdpeer3:9003/eureka/

