spring:
  application:
    name: servicediscovery
server:
  port: 9003

eureka:
  instance:
    hostname: sdpeer3
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eh:root@sdpeer1:9001/eureka/,http://eh:root@sdpeer2:9002/eureka/

