spring:
  application:
    name: servicediscovery
sever:
  port: 9002

eureka:
  instance:
    hostname: sdpeer2
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://sdpeer1:9001/eureka/,http://sdpeer3:9003/eureka/

